### ISSUE TITLE
Autocomplete not working on IE11

### ISSUE THREAD

**Issue by cnminh** [ideal-postcodes/ideal-postcodes-autocomplete#8]
Hi,

We are using IdealPostcode Autocomplete on our website. It works fine on Chrome, Edge, etc but it doesn't work on Internet Explorer 11. I didn't test with older versions of IE but in the document it says ```Internet Explorer 9 and above is supported```. Can you please have a look and advise on this.

How to test: Open the demo link in IE 11 https://ideal-postcodes.co.uk/autocomplete
-> The suggestion is not showing up.

Thanks so much!

**Comment by cblanc** [comment]
Hi @cnminh 

Thanks for opening the issue

The plugin itself appears to work on IE11 from our tests. I verified this again just now in a cleanroom render of a test page

![image](https://user-images.githubusercontent.com/2160685/57844910-34d8bb80-77d1-11e9-84b9-d29e83fb0628.png)

If you want to do the same, you can git clone this repo and `npm run test_server`. This will launch a HTTP server serving a clean HTML file with the plugin at http://localhost:8000/example/index.html

The issue you're actually observing is our unwillingness to accommodate IE at all on ideal-postcodes.co.uk. There's a lot of untranspiled ES5 there which will cause IE to halt due to syntax errors - including the autocomplete plugin. As you can imagine, a service offering targeting developers sees virtually zero IE traffic
